name: CI

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Git files setup
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install

      - name: Quality checks
        run: bun turbo lint typecheck

      - name: Test
        run: bun turbo test

      - name: Build libs
        run: bun turbo build
